00 translation_unit          ::= <statement_list>;
01 statement_list            ::= <statement>;
02 statement_list            ::= <statement_list> <statement>;
03 statement                 ::= <selection_statement>;
04 statement                 ::= <iteration_statement>;
06 statement                 ::= <expression>;
07 statement                 ::= <function_definition>;
08 statement                 ::= <target_definition>;
09 selection_statement       ::= <selection_statement_b>;
10 selection_statement       ::= <selection_statement_b> ELSE <compound_statement>;
11 selection_statement_b     ::= IF LPAREN <expression> RPAREN <compound_statement>;
12 selection_statement_b     ::= <selection_statement_b> ELIF LPAREN <expression> RPAREN <compound_statement>;
13 iteration_statement       ::= WHILE LPAREN <expression> RPAREN <compound_statement>;
14 iteration_statement       ::= FOR LPAREN <expression> COLON <expression> COLON <expression> RPAREN <compound_statement>;
15 iteration_statement       ::= FOR LPAREN ID IN ID RPAREN <compound_statement>;
16 expression                ::= <assignment_expression>;
17 assignment_expression     ::= <conditional_expression>
18 assignment_expression     ::= <postfix_expression> OP_ASSIGN <assignment_expression>
19 conditional_expression    ::= <logical_or_expression>
20 conditional_expression    ::= <logical_or_expression> QMARK <expression> COLON <conditional_expression>
21 logical_or_expression     ::= <logical_and_expression>
22 logical_or_expression     ::= <logical_or_expression> OR_OP <logical_and_expression>
23 logical_and_expression    ::= <equality_expression>
24 logical_and_expression    ::= <logical_and_expression> AND_OP <equality_expression>
25 equality_expression       ::= <relational_expression>
26 equality_expression       ::= <equality_expression> EQ_OP <relational_expression>
27 equality_expression       ::= <equality_expression> NE_OP <relational_expression>
28 relational_expression     ::= <additive_expression>
29 relational_expression     ::= <relational_expression> OP_L <additive_expression>
30 relational_expression     ::= <relational_expression> OP_G <additive_expression>
31 relational_expression     ::= <relational_expression> OP_LE <additive_expression>
32 relational_expression     ::= <relational_expression> OP_GE <additive_expression>
33 additive_expression       ::= <multiplicative_expression>
34 additive_expression       ::= <additive_expression> OP_ADD <multiplicative_expression>
35 additive_expression       ::= <additive_expression> OP_SUB <multiplicative_expression>
36 multiplicative_expression ::= <postfix_expression>
37 multiplicative_expression ::= <multiplicative_expression> OP_MUL <postfix_expression>
38 multiplicative_expression ::= <multiplicative_expression> OP_DIV <postfix_expression>
39 multiplicative_expression ::= <multiplicative_expression> OP_MOD <postfix_expression>
40 postfix_expression        ::= <primary_expression>
41 postfix_expression        ::= <postfix_expression> LPAREN <argument_expression_list> RPAREN
42 primary_expression        ::= IDENTIFIER COLON IDENTIFIER
43 primary_expression        ::= INT 
44 primary_expression        ::= FLOAT 
45 primary_expression        ::= STRING
46 primary_expression        ::= IDENTIFIER
47 function_definition       ::= DEF ID COLON ID LPAREN <identifier_list> RPAREN <compound_statement>
48 function_definition       ::= DEF ID LPAREN <identifier_list> RPAREN <compound_statement>
49 target_definition         ::= ID STRING COLON <identifier_list> <compound_statement>
50 target_definition         ::= ID COLON <identifier_list> <compound_statement>
51 identifier_list           ::= #blank#
52 identifier_list           ::= ID
53 identifier_list           ::= ID COLON ID
54 identifier_list           ::= <identifier_list> ID
55 identifier_list           ::= <identifier_list> ID COLON ID
56 argument_expression_list  ::= #blank#
57 argument_expression_list  ::= <assignment_expression>
58 argument_expression_list  ::= <argument_expression_list> COMMA <assignment_expression>
59 compound_statement        ::= INDENT DEDENT
60 compound_statement        ::= INDENT <statement_list> DEDENT




translation_unit::= <statement_list>;

statement_list::= <statement>
                | <statement_list> <statement>
                ;

statement::= <selection_statement>
           | <iteration_statement>
           | <expression>
           | <function_definition>
           ;

selection_statement::= <selection_statement_b>
                     | <selection_statement_b> ELSE <block>
                     ;

selection_statement_b::= IF LPAREN <expression> RPAREN <block>
                       | <selection_statement_b> ELIF LPAREN <expression> RPAREN <block>
                       ;

iteration_statement::= WHILE LPAREN <expression> RPAREN <block>
                     | FOR LPAREN <expression> COLON <expression> COLON <expression> RPAREN <block>
                     | FOR LPAREN ID IN ID RPAREN <block>
                     ;

expression::= <assignment_expression>
            ;

assignment_expression::= <conditional_expression>
                       | <postfix_expression> OP_ASSIGN <assignment_expression>
                       ;

conditional_expression::= <logical_or_expression>
                        | <logical_or_expression> QMARK <expression> COLON <conditional_expression>
                        ;

logical_or_expression::= <logical_and_expression>
                       | <logical_or_expression> OR_OP <logical_and_expression>
                       ;

logical_and_expression::= <equality_expression>
                        | <logical_and_expression> AND_OP <equality_expression>
                        ;

equality_expression::= <relational_expression>
                     | <equality_expression> EQ_OP <relational_expression>
                     | <equality_expression> NE_OP <relational_expression>
                     ;

relational_expression::= <additive_expression>
                       | <relational_expression> OP_L <additive_expression>
                       | <relational_expression> OP_G <additive_expression>
                       | <relational_expression> OP_LE <additive_expression>
                       | <relational_expression> OP_GE <additive_expression>
                       ;

additive_expression::= <multiplicative_expression>
                     | <additive_expression> OP_ADD <multiplicative_expression>
                     | <additive_expression> OP_SUB <multiplicative_expression>
                     ;

multiplicative_expression::= <postfix_expression>
                           | <multiplicative_expression> OP_MUL <postfix_expression>
                           | <multiplicative_expression> OP_DIV <postfix_expression>
                           | <multiplicative_expression> OP_MOD <postfix_expression>
                           ;

postfix_expression::= <primary_expression>
                    | <postfix_expression> LPAREN <argument_expression_list> RPAREN
                    ;

primary_expression::= IDENTIFIER COLON IDENTIFIER
                    | INT
                    | FLOAT
                    | STRING
                    | IDENTIFIER
                    ;

function_definition::= DEF ID COLON ID LPAREN <identifier_list> RPAREN <block>
                     | DEF ID LPAREN <identifier_list> RPAREN <block>
                     ;

target_definition::= ID STRING COLON <identifier_list> <block>
                   | ID COLON <identifier_list> <block>

identifier_list::= #blank#
                 | IDENTIFIER
                 | IDENTIFIER COLON IDENTIFIER
                 | <identifier_list> IDENTIFIER
                 | <identifier_list> IDENTIFIER COLON IDENTIFIER
                 ;

argument_expression_list::= #blank#
                          | <assignment_expression>
                          | <argument_expression_list> COMMA <assignment_expression>
                          ;


block::= INDENT DEDENT
       | INDENT <statement_list> DEDENT
       ;

